export const APP_CONFIG = {
  OTP_EXPIRY_MINUTES: 1,
  JWT_ACCESS_TOKEN_EXPIRY_DAYS: 7,
  JWT_REFRESH_TOKEN_EXPIRY_DAYS: 30,
  JWT_TEMP_TOKEN_EXPIRY_HOURS: 1,
  APP_NAME: 'Care4U',
  VERSION: '1.0.0',
};

export const OTP_EXPIRY_MS = APP_CONFIG.OTP_EXPIRY_MINUTES * 60 * 1000;

export const JWT_ACCESS_TOKEN_EXPIRY = '7d';
export const JWT_REFRESH_TOKEN_EXPIRY = '30d';
export const JWT_TEMP_TOKEN_EXPIRY = '1h';
